### PR TITLE
Update ffmpeg executable files to latest version n3.0

### PR DESCRIPTION
**Pull request by thuydx55**

### CODE REVIEW

**Comment by thuydx55** [comment]
Hi @hiteshsondhi88 @6uru, is there any update?

**Comment by hannanriaz009** [comment]
I want to use it over 64-bit device. Would love to have latest library changes available at gradle compile link, compile 'com.github.hiteshsondhi88.libffmpeg:FFmpegAndroid:0.2.5'
I am using this in my android studios project. 

When these pending PRs are expected to be merged in? :)

**Comment by 6uru** [comment]
@thuydx55 @hannanriaz009 

We are trying our best and would be testing the pull request and update you soon.

**Comment by thuydx55** [comment]
Did you guy finish testing?

**Comment by ruha9005** [comment]
Hey guys, please, merge this pull request..

**Comment by JayParikh20** [comment]
@thuydx55  Hey ,which plugins are enabled in this library?

**Comment by thuydx55** [comment]
You can run `-version` command in SampleApp to see what is enabled

**Comment by JayParikh20** [comment]
@thuydx55 Which Operating system are you using for build ffmpeg?

**Comment by thuydx55** [comment]
@JayParikh20 I'm using Ubuntu 14.04. You can try it by yourself but in my case, it takes 20 mins to build binary for each platform

**Comment by gouravd** [comment]
@thuydx55 Could you help me with the steps for building ffmpeg (3.0). The outputs are too big (>17mb) for our use and we only need very few features. So I assume if I build it by removing most of the stuff not required by me, I can reduce the size.

**Comment by ruha9005** [comment]
HELLO DEVS WAKE UP AND PLEASE MERGE THIS PR.

**Comment by hiteshsondhi88** [comment]
Hey @thuydx55 I need to decline as the binary didn't have LAME. So updating the project with n3.0.1 FFmpeg and with lame.

You can already check the updated binaries https://github.com/WritingMinds/ffmpeg-android/releases

**Comment by gouravd** [comment]
A quick question, does anything in CPUArch.java has to change for v0.3.4?

enum CpuArch {
    x86("dc9b832217acea7c7d8453d0f0d64cb6072323b1"),
    ARMv7("23744779c593150a272d67325962c3b3eae63b6a"),
    ARMv7_NEON("8b9c8d5e758c4f5a2ff26419787a89f0dd8911c1"),

**Pull request closed without merging**
